name: 'Terraform Apply on Main'

# This workflow runs only when a push happens on the main branch.
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository code.
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Installs and configures Terraform CLI.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 3: Initializes Terraform.
      - name: Terraform Init
        run: terraform init

      # Step 4: Applies the changes to your infrastructure.
      # The -auto-approve flag is necessary for non-interactive CI/CD runs.
      - name: Terraform Apply
        run: terraform apply -auto-approve
